name: deploy-react-app

on:
  push:
    branches:
      - master


jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
      -  run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      -  run: docker build -t moka/my-react-app -f Dockerfile.dev .
      -  run: docker run -e CI=true moka/my-react-app npm run test


    # Create deployment package (needed for elastic beanstalk)

    #   - name: Create deployment package
    #     run : zip -r deploy.zip . -x '*.git*'


    # Creating the configuration of the elastic beanstalk

    #   - name: deploy over the elastic beans
    #     uses: einaregilsson/beanstalk-deploy@v20  
    #     with: 
    #       aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
    #       aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
          
    #       application_name: "React-project"
    #       environment_name: "React-project-env"
    #       region: "us-east-1"
    #       version_label: ${{github.sha}}
    #       deployment_package: "deploy.zip"

