name: deploy-react-app

on:
  push:
    branches:
      - master


jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
      -  run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      -  run: docker build -t moka/my-react-app -f Dockerfile.dev .
      - run: docker run -e CI=true moka/my-react-app npm run test